### ISSUE TITLE
Hexo -> Typecho

### ISSUE THREAD

**Issue by NULL1945** [yuche/hexo-theme-kael#14]
Hi, I am fond of this theme, however I am a user of another blog system, Typecho. So, I try to adapt it to my blog. Here is it: [Typecho-theme-Kael](https://github.com/1995LZH/Typecho-theme-Kael) Thank you.

**Comment by yuche** [comment]
@1995LZH 

Hi，我看你的 repo 有中文，我还是直接和你说中文好了。

首先谢谢你的欣赏。不过正如我在 [#13](https://github.com/yuche/hexo-theme-kael/issues/13) 所言，这个主题很糟糕，不太推荐使用。原因如下：
1. 我写 Kael 的时候没有使用任何代码检测和辅助工具，加之当时我对 CSS 和 JavaScript 了解不深，所以代码的质量一团糟；
2. 使用了大量无意义的库和插件，严重拖慢了载入的时间和 render 的性能（如果你的网络条件不好，就很明显了）。现在看来 Kael 使用的大部分插件功能都可以自己手工写出来，根本用不上库的很多功能。如果现在我能用现在的前端工具和经验，例如 SCSS、ES6、Webpapck 等重写的话，估计性能和包的大小都会有 10 倍左右的提升和缩减（不是我牛逼，是原来的太糟糕……）；
3. 由于过多的库造成了许多冲突和 Bug，我好久弄过了，忘了许多，估计你折腾的过程中肯定有遇到；
4. 现在有了许多更优秀的主题。例如 Hexo 有一个特别好的 [Next](https://github.com/iissnan/hexo-theme-next)，还有一个我很喜欢的 [Lighting](http://hackll.com/2015/04/12/20-vim-tips/)。Hexo 原来默认的主题 Light 也是一个非常优秀的主题；
5. 有 Next 的珠玉在前，其实我也想不到有什么简洁风格的能比它更好了。我倒是想做一个基于 [Invision Now](http://www.invisionapp.com/now) 的设计理念，特效向 [Awwwards](http://www.awwwards.com/) 的网站们看齐那种华而不实类型的 Ghost 主题。脑子里有一个图景了，不过我手头上还有项目，今天周末又出去打了一天的 Dota。好累。

再次感谢你的欣赏。如果你确实喜欢 Kael 的设计理念和风格的话。我建议你自己不使用任何库（或者使用轻量级的）重写一次。如果你遇到了什么困难或者有什么问题，欢迎一起探讨和学习。：）

**Comment by NULL1945** [comment]
半年前第一次见到你的主题当时觉得这效果蛮不错的，就挺欣赏的。我在本地做过几个 Typecho 主题，但都不是我想要的效果，然后最近又萌生了再制作或者移植一个能上线使用的主题的想法。但是做了几个之后都不满意，于是到处找灵感，又想到了你的主题，看到你在 [#13](https://github.com/yuche/hexo-theme-kael/issues/13) 允许移植，而且基于 MIT 协议，于是我就移植了。现在，我对 Kael 挺满意的，我会尽量优化它的速度。另外，我看了 NEXT 和 Lighting，都不是我想要的效果。

由于我能力有限，所以阉割了 Kael 的很多功能，让我重构的话也是很难。能做到现在这个样子我已经挺满足的了。如果以后优化 Kael 时有不懂的，我再向你请教学习。：）
